user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /security

payment:
    resource: "@PaymentBundle/Resources/config/routing.yml"
    prefix:   /payment

web:
    resource: "@WebBundle/Resources/config/routing.yml"
    prefix:   /

#app:
#    resource: "@AppBundle/Resources/config/routing.yml"
#    prefix:   /api/v1
#    type: rest
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

