services:
    payment.invoiceService:
        class: PaymentBundle\Service\InvoiceService
        arguments: [ "@doctrine.orm.entity_manager", "PaymentBundle\Entity\Invoice", "@form.factory"]
#        arguments: ["@service_id", "plain_value", %parameter%]
#    payment.example:
#        class: PaymentBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
