PaymentBundle\Entity\Invoice:
    properties:
        amount:
            - NotBlank: ~
            - NotNull: ~
            - Length:
                min: 1
                max: 50
                minMessage: "Amount must be at least 1 characters length"
                maxMessage: "Amount cannot be longer than 50 characters length"