#app_homepage:
#    path:     /
#    defaults: { _controller: AppBundle:Default:index }
    
app_page:
    type: rest
    prefix: /v1
    resource: "AppBundle\\Controller\\PageController"
    name_prefix:  api_1_


