app_homepage:
    path:       /
    defaults:   { _controller: AppBundle:Payment:index }
    
app_mobop:
    type:       rest
    path:       /subscribe
    defaults:   { _controller: AppBundle:Payment:mobile }
    methods:    [POST]
    
