marchent_users_index:
    path:     /
    defaults: { _controller: "MarchentBundle:User:index" }
    methods:  GET

marchent_users_show:
    path:     /{id}/show
    defaults: { _controller: "MarchentBundle:User:show" }
    methods:  GET

marchent_users_new:
    path:     /new
    defaults: { _controller: "MarchentBundle:User:new" }
    methods:  [GET, POST]

marchent_users_edit:
    path:     /{id}/edit
    defaults: { _controller: "MarchentBundle:User:edit" }
    methods:  [GET, POST]

marchent_users_delete:
    path:     /{id}/delete
    defaults: { _controller: "MarchentBundle:User:delete" }
    methods:  DELETE
